color_scheme = {
    "dark_mode": False,
    "colors": {
        "light": {
            "application/window_and_frame_color": "#7C889C",
            "unselected_switch_buttons_background_color": "#697283",
            "toggle_switch_color": "white",
            "slider_background_color": "#7C889C",
            "slider_bar_fill":"#697283",
            "label_font_color/fg": "black",
            "button_font_color/fg": "white",
            "focus_button_fg_light": "white",
            "unselected_cam_focus_and_select_buttons": "grey",
            "unselected_settings_button": "#555",
            "button_bg": "#697283",
            "button_bg_light": "#697283",
            "selected_color": "#24D215",
            "light_green_bg": "#24D215",
            "slider_knob_color": "#24D215",
            "frame_outline_color": "black",
            "settings_select_buttons_inactive": "grey",
            "focus_button_bg_light_inactive":"grey",
            "focus_button_bg_light_active":"#24D215",
            "apply_changes_background": "red",
            "fullscreen_button_bg": "#4a4a4a",
            "fullscreen_button_fg": "white"
        },
        "dark": {
            "application/window_and_frame_color": "#1A1A1A",
            "unselected_switch_buttons_background_color": "#7C889C",
            "toggle_switch_color": "white",
            "slider_background_color": "#1A1A1A",
            "slider_bar_fill":"#7C889C",
            "label_font_color/fg": "white",
            "button_font_color/fg": "white",
            "focus_button_fg_dark": "white",
            "unselected_cam_focus_and_select_buttons": "grey",
            "unselected_settings_button": "#697283",
            "button_bg": "#7C889C",
            "button_bg_dark": "#7C889C",
            "selected_color": "#006400",
            "dark_green_bg": "#006400",
            "slider_knob_color": "#006400",
            "frame_outline_color": "white",
            "settings_select_buttons_inactive": "#697283",
            "focus_button_bg_dark_inactive": "#697283",
            "focus_button_bg_dark_active": "#006400",
            "apply_changes_background": "#8B0000",
            "fullscreen_button_bg": "#2a2a2a",
            "fullscreen_button_fg": "white"
        }
    }
}
